### ISSUE TITLE
[BUG] Duplicate file "Nuclear Utilities.cfg" causes unlock issues for nuc batt

### ISSUE THREAD

**Issue by sundhaug92** [Monniasza/SSTO-Project#2]
What has gone wrong
---
Try to unlock the nuclear batteries

How to recreate
---
If it works one time, you'll have to redo it (sometimes)

Put log here
---

**Comment by Monniasza** [comment]
Fixed: https://spacedock.info/mod/2417/SSTO%20Project/download/1.4.5

**Comment by sundhaug92** [comment]
Thanks, will you update the code in the repo?

**Comment by Monniasza** [comment]
Yes
