### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dhodges405** [Monniasza/SSTO-Project#3]
What has gone wrong
---I am unable to install or update mod.  get the same message everytime.   Not sure if it is something on my side or not.  but the message is :  

How to recreate
---

Put log here
---
![mod](https://github.com/Monniasza/SSTO-Project/assets/145096356/3d891290-aa3b-48b4-b143-a0b1fe9e86d7)

![Capture](https://github.com/Monniasza/SSTO-Project/assets/145096356/225f5103-3cf6-499a-a60b-2ed0d9d6e6c7)

**Comment by Monniasza** [comment]
@dhodges405 I suspect that your file got corrupted. Also, please specify the title of the issue

**Comment by Monniasza** [comment]
@dhodges405 I've just updated SSTO Project. Check out soon if version 1.6.0 comes out.

**Comment by Monniasza** [comment]
@dhodges405 Download newest version of SSTO Project. It is fixed
